### ISSUE TITLE
Broken Links 

### ISSUE THREAD

**Issue by miracleburt** [barricklab/breseq#312]
Hi! I've noticed that a lot if not all the links within the tutorials are broken. I've tried using different computers, restarting, and even searching up the links but nothing seems to be working. Can anyone help or is anyone else having this issue with all the broken links?

**Comment by jeffreybarrick** [comment]
Thanks for reporting the problem!

It looks like these are the ones beginning `http://barricklab.org/release` like this one?

[Download REL606.gbk via this link](http://barricklab.org/release/breseq_tutorial/REL606.gbk.gz)

It looks like this is due to a web server migration issue. I'll see if I can fix things and/or link to files posted in a place that will be more stable in the future.

Did you notice any other types of broken links? 

(It looks like the one at the top tp the EMBO course is also broken because they may have taken it down after so much time.)

**Comment by jeffreybarrick** [comment]
I think the links should be working now. Let me know if you find any other problems.

**Comment by miracleburt** [comment]
That's correct! However, for me at least the links are still not working.
Even when I tried clicking on the one you linked in the email it took me to
a page not found. This is something that I've encountered with all of the
links within the tutorials. One in particular that I needed to continue
with the tutorial is the reference files in tutorial #3. Thank you for
responding!

Miracle

**Comment by jeffreybarrick** [comment]
Hi @miracleburt,

There seem to be two levels of possible problems. 

The first was a web server problem. That should be fixed. You can access all of the tutorial files in this folder:
https://barricklab.org/release/breseq_tutorial/

The second problem is that Chrome (and possibly other browsers) are blocking clicking on download links that begin http:// when they detect that the server supports https://. Fixing this will have to wait until a breseq update when I can change those links in the manual. In the meantime, I believe that if you right-click and copy the link and then past it into your browser URL pane and hit return that it will still download the file.

**Comment by jeffreybarrick** [comment]
I uploaded a new version of the docs here, so I think the links should work in that now:
https://barricklab.org/twiki/pub/Lab/ToolsBacterialGenomeResequencing/documentation/
(You might need to reload the pages to keep your browser from using a cached version.)
